### PR TITLE
allow the building of universal wheels

### PR DESCRIPTION
**Pull request by graingert**
Distribute using:

`python setup.py sdist bdist_wheel register upload`

### CODE REVIEW

**Comment by mk-fg** [comment]
Thanks.

I did want to start using wheels for this project and others, but never made it to the first "educate myself about what wheels are and how to use them" step so far.
I'll try to fix that gap first and then will merge the change, as I'd rather know about what I'm doing here first.

**Comment by tdruez** [comment]
+1, a wheel would be nice ;)

**Comment by graingert** [comment]
@mk-fg It's been a while...

**Comment by mk-fg** [comment]
Yeah, and I still haven't got around to learning anything about python wheels, how they work, what kind of PKI setup they need and why they even matter...

Possible options:

- Fork the thing into something like "pyaml-on-wheels" and use the fork instead, given that this one is clearly not that well-maintained. Downside: forks breed chaos.

- Take over the project and PyPI entry. Downside: current users (if any) didn't ask for this, all sorts of risks.

- Wait for when I'll get around to finally applying that trivial one-liner. Downside: Half-Life 3 might come out first.

I do realize it's rather trivial task though, will try to fix soonish, thanks for reminder, and sorry that it's that bad.

**Comment by graingert** [comment]
> how they work

It's a zip file, with a JSON file that contains everything that the setup.py used to generate it contained.

> what kind of PKI setup they need

None, they don't need any new PKI setup. If you've got package signing setup for your sdist bdist_wheel will pick it up.

> and why they even matter...

They are a lot faster to install and run, (no sdist step, easier to cache, pregenerated pyc files etc.)

**Comment by graingert** [comment]
@mk-fg see http://pythonwheels.com/ for more info

**Comment by mk-fg** [comment]
Seem to work, and is very easy indeed, will try to not forget bdist_wheel on updates, if any.

Thanks for the tips and pointing out the issue.
Sorry that it took such unreasonably long time.

**Comment by tdruez** [comment]
@mk-fg That's great, thanks :)

**Pull request merged**
